/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return all books */
        get: operations["books"];
        put?: never;
        /** @description Create a new book */
        post: operations["createBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return a specific book by ID */
        get: operations["book"];
        put?: never;
        post?: never;
        /** @description Delete specific book by ID */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description BooksResponse model */
        BooksResponse: {
            data?: components["schemas"]["BookEntity"];
            /** @description Metadata */
            meta?: {
                /**
                 * Format: int32
                 * @description Total count of books
                 */
                total_records?: number;
            };
        };
        /** @description BookEntity model */
        BookEntity: {
            /**
             * Format: int32
             * @description Unique identifier for the book
             * @example 1
             */
            id?: number;
            /**
             * @description Title of the book
             * @example The Great Gatsby
             */
            title?: string;
            /**
             * @description Author of the book
             * @example F. Scott Fitzgerald
             */
            author?: string;
            /**
             * Format: date-time
             * @description Date the book was created
             */
            created_at?: string;
            /**
             * Format: date-time
             * @description Date the book was last updated
             */
            updated_at?: string;
        };
        /** @description Create a new book */
        createBook: {
            /** @description Book title */
            title: string;
            /** @description Book author */
            author: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    books: {
        parameters: {
            query?: {
                /** @description Filter by created AT field */
                "filters[created_at]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return all books */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BooksResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["createBook"];
            };
        };
        responses: {
            /** @description Create a new book */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookEntity"];
                };
            };
            /** @description KittenBitesError */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    book: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Return a specific book by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookEntity"];
                };
            };
            /** @description KittenBitesError */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Book not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delete specific book by ID */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
