/* tslint:disable */
/* eslint-disable */
/**
 * The API title to be displayed on the API homepage.
 * A description of the API.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: anton.i@hey.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * BookEntity model
 * @export
 * @interface BookEntity
 */
export interface BookEntity {
    /**
     * Unique identifier for the book
     * @type {number}
     * @memberof BookEntity
     */
    'id'?: number;
    /**
     * Title of the book
     * @type {string}
     * @memberof BookEntity
     */
    'title'?: string;
    /**
     * Author of the book
     * @type {string}
     * @memberof BookEntity
     */
    'author'?: string;
    /**
     * Date the book was created
     * @type {string}
     * @memberof BookEntity
     */
    'created_at'?: string;
    /**
     * Date the book was last updated
     * @type {string}
     * @memberof BookEntity
     */
    'updated_at'?: string;
}
/**
 * BooksResponse model
 * @export
 * @interface BooksResponse
 */
export interface BooksResponse {
    /**
     * 
     * @type {BookEntity}
     * @memberof BooksResponse
     */
    'data'?: BookEntity;
    /**
     * 
     * @type {BooksResponseMeta}
     * @memberof BooksResponse
     */
    'meta'?: BooksResponseMeta;
}
/**
 * Metadata
 * @export
 * @interface BooksResponseMeta
 */
export interface BooksResponseMeta {
    /**
     * Total count of books
     * @type {number}
     * @memberof BooksResponseMeta
     */
    'total_records'?: number;
}
/**
 * Create a new book
 * @export
 * @interface CreateBook
 */
export interface CreateBook {
    /**
     * Book title
     * @type {string}
     * @memberof CreateBook
     */
    'title': string;
    /**
     * Book author
     * @type {string}
     * @memberof CreateBook
     */
    'author': string;
}

/**
 * BooksApi - axios parameter creator
 * @export
 */
export const BooksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Return a specific book by ID
         * @param {number} id Book ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        book: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('book', 'id', id)
            const localVarPath = `/api/books/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return all books
         * @param {string} [filtersCreatedAt] Filter by created AT field
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        books: async (filtersCreatedAt?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/books`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (filtersCreatedAt !== undefined) {
                localVarQueryParameter['filters[created_at]'] = filtersCreatedAt;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new book
         * @param {CreateBook} createBook 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBook: async (createBook: CreateBook, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createBook' is not null or undefined
            assertParamExists('createBook', 'createBook', createBook)
            const localVarPath = `/api/books`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createBook, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete specific book by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBook: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteBook', 'id', id)
            const localVarPath = `/api/books/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BooksApi - functional programming interface
 * @export
 */
export const BooksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BooksApiAxiosParamCreator(configuration)
    return {
        /**
         * Return a specific book by ID
         * @param {number} id Book ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async book(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BookEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.book(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BooksApi.book']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return all books
         * @param {string} [filtersCreatedAt] Filter by created AT field
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async books(filtersCreatedAt?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BooksResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.books(filtersCreatedAt, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BooksApi.books']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create a new book
         * @param {CreateBook} createBook 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBook(createBook: CreateBook, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BookEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBook(createBook, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BooksApi.createBook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete specific book by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBook(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBook(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BooksApi.deleteBook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BooksApi - factory interface
 * @export
 */
export const BooksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BooksApiFp(configuration)
    return {
        /**
         * Return a specific book by ID
         * @param {number} id Book ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        book(id: number, options?: RawAxiosRequestConfig): AxiosPromise<BookEntity> {
            return localVarFp.book(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Return all books
         * @param {string} [filtersCreatedAt] Filter by created AT field
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        books(filtersCreatedAt?: string, options?: RawAxiosRequestConfig): AxiosPromise<BooksResponse> {
            return localVarFp.books(filtersCreatedAt, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a new book
         * @param {CreateBook} createBook 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBook(createBook: CreateBook, options?: RawAxiosRequestConfig): AxiosPromise<BookEntity> {
            return localVarFp.createBook(createBook, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete specific book by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBook(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteBook(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BooksApi - object-oriented interface
 * @export
 * @class BooksApi
 * @extends {BaseAPI}
 */
export class BooksApi extends BaseAPI {
    /**
     * Return a specific book by ID
     * @param {number} id Book ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public book(id: number, options?: RawAxiosRequestConfig) {
        return BooksApiFp(this.configuration).book(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return all books
     * @param {string} [filtersCreatedAt] Filter by created AT field
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public books(filtersCreatedAt?: string, options?: RawAxiosRequestConfig) {
        return BooksApiFp(this.configuration).books(filtersCreatedAt, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a new book
     * @param {CreateBook} createBook 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public createBook(createBook: CreateBook, options?: RawAxiosRequestConfig) {
        return BooksApiFp(this.configuration).createBook(createBook, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete specific book by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public deleteBook(id: number, options?: RawAxiosRequestConfig) {
        return BooksApiFp(this.configuration).deleteBook(id, options).then((request) => request(this.axios, this.basePath));
    }
}



